object_geometries:
  table      : {box: [2.0, 2.0, 0.1], color: [0.5,0.5,0.5,1.0], position: [ 0.0,0.0,0.0], quaternion: [0, 0, 0, 1]}
  box        : {box: [0.2, 0.2, 0.2], color: [1.0,0.0,0.0,1.0], position: [-1.0,0.0,0.2], quaternion: [0, 0, 0, 1]}
  big_box    : {box: [0.4, 0.4, 1], color: [1.0,0.0,0.0,0.3], position: [-1.0,0.0,0.2], quaternion: [0, 0, 0, 1]}
  rectangle  : {box: [0.2, 0.5, 0.5], color: [1.0,0.0,0.0,1.0], position: [-1.0,0.0,0.2], quaternion: [0, 0, 0, 1]}
  sphere     : {sphere: 0.025, color: [1,0.0,0.0,0.0], position: [0.0,0.0,0.0], quaternion: [0, 0, 0, 1]}

