base_frame: "base_link"
tool_frame: "open_tip"
test_links: [wrist_3_link, forearm_link, flange, wrist_1_link] #[wrist_3_link, forearm_link, open_tip, wrist_1_link]

minimum_distance: 0.3
reaction_time: 0.15 #0.1 #0.3
human_velocity: 1.6
maximum_cartesian_acceleration: 2.5 #0.1

time_remove_old_objects: 1.5

#Information to publish obstacles
publish_obstacles: true
sphere_radius: 0.15
sphere_rgba: [1.0,1.0,1.0,0.2]
